### ISSUE TITLE
Sending close_notify while closing the connection.

### ISSUE THREAD

**Issue by ayushbindlish** [tempesta-tech/tls-perf#11]
Hi, is it possible to send close notify while tls-perf closes a connection?

**Comment by krizhanovsky** [comment]
Hi @ayushbindlish ,

`tls-perf` sends close notify alerts if tickets are enabled. For example with client:
```
$ ./tls-perf --tickets on -n 1 127.0.0.1 4433
```
The server prints message about close notify reception:
```
$ openssl s_server -accept :4433 -cert cert.pem -key key.pem -debug -msg
.....
read from 0x55f1223c0710 [0x55f1223d29d8] (26 bytes => 26 (0x1A))
0000 - 9a 0f da 80 82 20 a7 42-24 ca cc 12 92 7e 30 e7   ..... .B$....~0.
0010 - 0b 75 3b e1 13 c8 83 18-b1 be                     .u;.......
<<< TLS 1.2, Alert [length 0002], warning close_notify
    01 00
DONE
shutting down SSL
CONNECTION CLOSED
read from 0x55f1223c0690 [0x55f1223d0d23] (5 bytes => -1 (0xFFFFFFFFFFFFFFFF))
ERROR
shutting down SSL
CONNECTION CLOSED
```

However, note that `tls-perf` deals with TCP connections in a very aggressive manner, especially in connections closing to be able to establish as many new connections as possible, which leads to the `ERROR` in the message above. This behaviour might also lead to plenty of orphaned TCP connections (see https://github.com/tempesta-tech/tempesta/issues/1432 for details).

**Comment by krizhanovsky** [comment]
Please feel free to reopen the issue if the question is still not answered.
