### ISSUE TITLE
Question: Is there a way to compile it on apple m1?

### ISSUE THREAD

**Issue by ayushbindlish** [tempesta-tech/tls-perf#12]
Can I compile it on apple m1?

**Comment by ikoveshnikov** [comment]
There  are just two major dependencies: `openssl` library  and `epoll` call. `epoll` is not supported by macos and `kqueue` must be used instead. They are very close to each other, and porting to `kqueue` shouldn't be hard. Without it the tool can't be compiled and started on macos.

Not familiar with macos, but `openssl` library should be available there. There are a lot of optimistations for various architectures inside `openssl`, but  the `tls-perf` itself doesn't use any processor-specific optimizations.

So macos is the problem, not the M1 processor.

**Comment by krizhanovsky** [comment]
Please feel free to reopen the issue if the question is still not answered.
